_target_: locodiff.agent.Agent
_recursive_: false

optimization:
  _target_: torch.optim.AdamW
  lr: 1e-4
  betas: [0.9, 0.999]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${max_train_steps}

max_train_steps: ${max_train_steps}
eval_every_n_steps: ${eval_every_n_steps}
num_sampling_steps: ${n_timesteps}
sigma_data: ${sigma_data}
sigma_min: 0.001
sigma_max: 80
use_ema: ${use_ema}
decay: ${decay}
device: ${device}
update_ema_every_n_steps: ${update_ema_every_n_steps}

obs_dim: ${obs_dim}
pred_obs_dim: ${pred_obs_dim}
action_dim: ${action_dim}
T: ${T}
T_cond: ${T_cond}
T_action: ${T_action}
num_envs: ${env.num_envs}
sim_every_n_steps: ${sim_every_n_steps}
weight_decay: ${weight_decay}
cond_lambda: ${cond_lambda}
cond_mask_prob: ${cond_mask_prob}

model:
  _target_: locodiff.wrapper.GCDenoiser
  _recursive_: false

  sigma_data: ${sigma_data}

  inner_model:
    _target_: locodiff.transformer.DiffusionTransformer
    obs_dim: ${obs_dim}
    pred_obs_dim: ${pred_obs_dim}
    goal_dim: ${goal_dim}
    act_dim: ${action_dim}
    d_model: ${hidden_dim}
    nhead: ${n_heads}
    num_layers: ${num_hidden_layers}
    T: ${T}
    T_cond: ${T_cond}
    device: ${device}
    cond_mask_prob: ${cond_mask_prob}
    dropout: ${dropout}

dataset_fn:
  _target_: data.dataloader.get_raisim_train_val
  data_directory: ${data_path}
  obs_dim: ${obs_dim}
  train_fraction: 0.95
  random_seed: ${seed}
  device: ${device}
  window_size: ${T_cond}
  future_seq_len: ${T}
  train_batch_size: 512
  test_batch_size: 512
  num_workers: 4
