_target_: beso.agent.score_wrappers.GCDenoiser
_recursive_: false

sigma_data: ${sigma_data}
T: ${T}
T_cond: ${T_cond}

inner_model:
  _target_: beso.agent.diffusion_transformer.DiffusionTransformer
  obs_dim: ${obs_dim}
  pred_obs_dim: ${pred_obs_dim}
  act_dim: ${action_dim}
  d_model: ${hidden_dim}
  nhead: ${n_heads}
  num_layers: ${num_hidden_layers}
  T: ${T}
  T_cond: ${T_cond}
  device: ${device}
  cond_mask_prob: ${cond_mask_prob}
  dropout: ${dropout}
