_target_: beso.agents.diffusion_agents.k_diffusion.score_wrappers.GCDenoiser
_recursive_: false

sigma_data: ${sigma_data}

inner_model:
  _target_: beso.agents.diffusion_agents.k_diffusion.score_gpts.DiffusionGPT
  state_dim: ${obs_dim}
  action_dim: ${action_dim}
  goal_dim: ${goal_dim}
  embed_dim: ${hidden_dim}
  n_layers: ${num_hidden_layers}
  obs_seq_len: ${window_size}
  future_seq_len: ${future_seq_length}
  embed_pdrob: 0
  goal_drop: ${cond_mask_prob}
  attn_pdrop: ${attn_pdrop} # 0.3
  resid_pdrop: ${resid_pdrop} #.3
  # Architecture details
  n_heads: ${n_heads}
  device: ${device}
  