_target_: beso.agents.diffusion_agents.k_diffusion.score_wrappers.GCDenoiser
_recursive_: false

sigma_data: ${sigma_data}

inner_model:
  _target_: beso.agents.diffusion_agents.k_diffusion.conditional_unet1d.ConditionalUnet1D
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  future_seq_length: ${future_seq_length}
  diffusion_step_embed_dim: 256
  down_dims: [256, 512, 1024]
  