_target_: locodiff.wrapper.GCDenoiser
_recursive_: false

sigma_data: ${sigma_data}

inner_model:
  _target_: locodiff.transformer.DiffusionTransformer
  obs_dim: ${obs_dim}
  pred_obs_dim: ${pred_obs_dim}
  goal_dim: ${goal_dim}
  act_dim: ${action_dim}
  d_model: ${hidden_dim}
  nhead: ${n_heads}
  num_layers: ${num_hidden_layers}
  T: ${T}
  T_cond: ${T_cond}
  device: ${device}
  cond_mask_prob: ${cond_mask_prob}
  dropout: ${dropout}