hydra:
  run:
    dir: logs/classifier/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  entity: reeceomahoney
  project: locodiff_classifier

model_store_path: logs/2024-05-03/22-08-03
train_steps: 5e4
test_interval: 5e2
log_interval: 1e2
save_interval: 1e3
inference_steps: 10

classifier:
  _target_: locodiff.classifier.Classifier
  input_dim: 48
  d_model: 256
  nhead: 4
  num_layers: 2
  T: 125
  T_cond: 2
  value_mean: 60
  value_std: 22
  device: cuda
# classifier:
#   _target_: locodiff.classifier.ClassifierMLP
#   input_dim: 122
#   hidden_dims: [256, 256]
#   value_mean: 60
#   value_std: 22
#   device: cuda
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  betas: [0.9, 0.999]