defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

model_store_path: logs/2024-04-18/12-41-24
log_wandb: True

num_runs: 50
n_inference_steps: 3
sigma_min: 0.1
sigma_max: 1
cond_lambda: 1
device: cuda

# chose what to evaluate
test_rollout: False
test_timestep_mse: False
test_total_mse: False
test_observation_error: False
visualize x-y trajectory: True
