defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

model_store_path: logs/raisim/runs/2024-03-11/18-02-07
log_wandb: True

num_runs: 50
n_inference_steps: 3
sigma_min: 0.1
sigma_max: 1
cond_lambda: 1
device: cuda

# chose what to evaluate
test_diffusion_steps: False
test_observation_error: False
test_rollout: True
