defaults:
  - agents: beso_raisim
  - workspaces: raisim_manager
  - _self_

log_dir: logs/raisim/
plot_dir: plots/raisim/
plot_name: ${now:%Y-%m-%d}.png
data_path: fwd

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

group: first_tests

wandb:
  entity: reeceomahoney
  project: beso_experiments

# general params
device: 'cuda'
seed: 6
T: 20
T_cond: 2
T_action: 1

action_dim: 12
obs_dim: null  # will be set automatically
pred_obs_dim: null  # will be set automatically
goal_dim: 1

# policy model params
hidden_dim: 128
use_spectral_norm: false
num_hidden_layers: 4
train_method: 'steps'
max_train_steps: 1e6
max_epochs: 100
eval_every_n_steps: 1000
sim_every_n_steps: 5000

# BESO hyperparameters
attn_pdrop: 0.05
resid_pdrop: 0.05
n_heads: 8
use_ema: True
decay: 0.999 
update_ema_every_n_steps: 1
sigma_data: 0.5 
cond_mask_prob: 0.1
cond_lambda: 2 # only required for inference of CFG-BESO
n_timesteps: 3 # number of diffusion steps during inference

env:
  render: True
  num_envs: 30
  num_threads: 'auto'
  simulation_dt: 0.005
  control_dt: 0.04
  max_time: 10000
  enable_dynamics_randomization: False
  action_scaling: 1.0
  use_actuator_network: True
  server_port: 8080
  early_termination: True
  normalize_observation: False

  velocity_command:
    limit_heading_velocity: 1.0
    limit_lateral_velocity: 0.75
    limit_yaw_rate: 1.25

    # Less than this is considered to be a zero velocity command
    limit_velocity_magnitude: 0.1

    # These values are rescaled if their sum is not equal to 1
    probability_zero_command: 0.2
    probability_heading_command: 0.0
    probability_lateral_command: 0.0
    probability_yaw_command: 0.0
    probability_direction_command: 0.0
    probability_constant_command: 0.8   # includes all three velocities

    # Time range in seconds when the next command is sampled
    command_sampling_time_min: 3.0
    command_sampling_time_max: 4.0

  reward:
    base_linear_velocity_tracking:
      coeff: 0.0
    base_angular_velocity_tracking:
      coeff: 0.0