program: scripts/training.py
project: beso_experiments
name: beso_raisim
method: bayes
metric:
  goal: minimize
  name: total_mse
parameters:
  max_train_steps: 
    value: 2e4
  T:
    values: [1, 2, 3, 4]
  T_cond:
    values: [1, 2, 3, 4]
  hidden_dim:
    values: [128, 256, 512]
  num_hidden_layers:
    values: [2, 4, 6]
  n_heads:
    values: [4, 8, 16]
    
  
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}