_target_: beso.workspaces.raisim_workspace.RaisimManager
_recursive_: false

dataset_fn:
  _target_: beso.envs.raisim.data.dataloader.get_raisim_train_val
  data_directory: ${data_path}
  obs_dim: ${obs_dim}
  train_fraction: 0.95
  random_seed: ${seed}
  device: ${device}
  window_size: ${window_size}
  goal_conditional: ${goal_conditional}
  future_seq_len: ${future_seq_length}
  only_sample_tail: false # true change again 
  only_sample_seq_end: False 

seed: ${seed}
train_batch_size: 1024
test_batch_size: 1024
num_workers: 4
eval_n_times: 1
eval_n_steps: 300
device: ${device}
scale_data: ${scale_data}
train_fraction: 0.95
use_minmax_scaler: true
